services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=Abcd1234.
      - MYSQL_DATABASE=Prueba
      - MYSQL_USER=user
      - MYSQL_PASSWORD=Abcd1234.
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
