version: '3.1'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./moodle:/var/www/html/moodle
      - moodledata:/var/moodledata
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: Abcd1234.
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  moodledata:
  dbdata:

