services:
  web:
    image: php:8.2-apache
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
    build:
      context: .
      dockerfile: Dockerfile

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Abcd1234.
      - MYSQL_DATABASE=Prueba
      - MYSQL_USER=user
      - MYSQL_PASSWORD=Abcd1234.
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:

